[package]
org = "ballerinax"
name = "postgresql"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "PostgreSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "postgresql-native"
version = "@toml.version@"
path = "../native/build/libs/postgresql-native-@project.version@.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "@sql.version@"
path = "./lib/sql-native-@sql.native.version@.jar"

