[package]
org = "ballerinax"
name = "postgresql"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["client", "network", "SQL", "RDBMS", "Vendor/PostgreSQL", "Area/Database", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "postgresql-native"
version = "@toml.version@"
path = "../native/build/libs/postgresql-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "@sql.version@"
path = "./lib/sql-native-@sql.native.version@.jar"

