[package]
org = "ballerinax"
name = "postgresql"
version = "1.16.2"
authors = ["Ballerina"]
keywords = ["client", "network", "SQL", "RDBMS", "Vendor/PostgreSQL", "Area/Database", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "postgresql-native"
version = "1.16.2"
path = "../native/build/libs/postgresql-native-1.16.2-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.16.0"
path = "./lib/sql-native-1.16.0.jar"

