[package]
org = "ballerinax"
name = "postgresql"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/postgresql-native-1.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.0-20210904-201300-14ea373.jar"

[[platform.java11.dependency]]
path = "./lib/postgresql-42.2.20.jar"
scope = "testOnly"
