[package]
org = "ballerinax"
name = "postgresql"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../postgresql-native/build/libs/postgresql-native-@toml.version@.jar"
groupId = "org.ballerinalang"
artifactId = "postgresql-native"
version = "@project.version@"

[[platform.java11.dependency]]
path = "@project.path@/repo/bala/ballerina/sql/@stdlib.sql.version@/java11/platform/java11/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "@stdlib.sql.native.version@"

[[platform.java11.dependency]]
path = "./lib/postgresql-42.2.18.jar"
artifactId = "postgresql-connector-java"
groupId = "postgresql"
scope = "testOnly"
version = "42.2.18"
